app:
  name: "web_app"
  mode: "dev"
  port: 8071
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "yewenwei"
  db_name: "gin"
  max_open_connection: 200
  max_idle_connection: 10
redis:
  host: "127.0.0.1"
  password: ""
  port: 6379
  db: 0
  pool_size: 0